### ISSUE TITLE
How the examples are selected for the few-shot prompting?

### ISSUE THREAD

**Issue by qfkkwgd** [wenhuchen/Program-of-Thoughts#1]
Thanks for your amazing work! The results are really surprising.

I noticed that in your main results table you compared with previous works (e.g. CoT). Did you use the same examples as theirs? If not, will the comparsion still be fair?

**Comment by wenhuchen** [comment]
For the CoT experiments we ran,  we use the same examples. For the results we copied from the original CoT and self-consistency papers, we don't know what they use. But I assume it's also somewhat tuned to achieve good results. We use almost the same shots. According our our observation, the variance won't be too large even if you just randomly select some examples.

**Comment by qfkkwgd** [comment]
Thanks for your feedback!

Some more questions:

1. I re-checked "CoT" paper, and found all their results on math tasks are obtained from 8-sample few-shot prompting setting, including SVAMP. But in your paper, you mentioned "For simple datasets like SVAMP (Patel et al., 2021) and FinQA (Chen et al., 2021b), we only use 4 shots". I don't think it is a fair comparison here.

2. I tried your script for SVAMP (run_svamp.py), and found the first example in the prompt is actually from SVAMP test set.
Here is the first example for SVAMP prompting:
# Passage: Each pack of dvds costs 76 dollars. If there is a discount of 25 dollars on each pack
# Question: How much do you have to pay to buy each pack?
The exactly same example appears at Line 773 in this link https://github.com/arkilpatel/SVAMP/blob/main/data/mawps-asdiv-a_svamp/dev.csv
Are the results still solid if one of the prompt is actually from the test set of SVAMP?

**Comment by wenhuchen** [comment]
1. We use less examples for SVAMp, it's even better, right?
2. We have multiple versions for SVAMP. I will upload another version which did not contain any test set question.

**Comment by wenhuchen** [comment]
Hi there, I just updated [run_svamp.py](https://github.com/wenhuchen/Program-of-Thoughts/blob/main/run_svamp.py) with my hand-written 7 examples, no overlap with the test set all. I reran the experiments to get an even higher score of 85.2. The output is in [svamp_s0_e-1_11_24_14_38.jsonl](https://github.com/wenhuchen/Program-of-Thoughts/blob/main/outputs/svamp_s0_e-1_11_24_14_38.jsonl). 

Please check out the new version! If you have any further question, feel free to post it here or send me an email.
