### ISSUE TITLE
Difference with PAL?

### ISSUE THREAD

**Issue by jordane95** [wenhuchen/Program-of-Thoughts#3]
Hi,

It's a smart idea to combine LLMs with external tools using PL as an interface! However, I aslo read another paper [PAL](https://arxiv.org/abs/2211.10435) before and find the approach quiet similar.

May I know the difference between PoT and PAL, except for more evaluation datasets? Thanks!

**Comment by wenhuchen** [comment]
Not much difference, we came out roughly at the same day.
