### ISSUE TITLE
Table format in prompt

### ISSUE THREAD

**Issue by hideodeo** [wenhuchen/Program-of-Thoughts#4]
<img width="516" alt="Screenshot 2023-05-10 at 12 02 24 PM" src="https://github.com/wenhuchen/Program-of-Thoughts/assets/23382313/238cf685-b8ad-406e-91c6-3f2ab9ca7602">

Hello. I see in run_finqa.py that you have formatted a table as in the screenshot instead of linearizing table rows as FinQA authors do. An example of linearized table rows is below. 

"date the december 2016 of altria group inc . is $ 286.61 ; the december 2016 of altria group inc . peer group is $ 192.56 ; the december 2016 of s&p 500 is $ 198.09 ;"

My question is:
Are there particular reasons you formatted tables in your way? Any benefits such as performance improvement? Could linearized table rows rather confuse an LLM? Thank you!

**Comment by wenhuchen** [comment]
There is no particular reasons to format the table in this way. I have tested a few different formats but got no performance difference. I would encourage you to test different formats to see its performance change.

**Comment by hideodeo** [comment]
Thanks for your quick response!
