### ISSUE TITLE
About TabMWP Baselines

### ISSUE THREAD

**Issue by QiushiSun** [wenhuchen/Program-of-Thoughts#6]
Thanks for releasing this amazing repo! May I ask if you can provide the CoT baselines for TabWMP, similar to the other three Table Understanding tasks like `run_tatqa_cot_gpt3.py`?

**Comment by wenhuchen** [comment]
I searched a bit but couldn't find it on the machine anymore. I believe I built it upon the codebase in https://github.com/lupantech/PromptPG/blob/main/run_gpt3/run_gpt3.py. It should be fairly easy to replicate it.
