### ISSUE TITLE
Why only evaluate on the final question for ConvFinQA?

### ISSUE THREAD

**Issue by SeanNaren** [wenhuchen/Program-of-Thoughts#7]
Hey! I was curious why when evaluating ConvFinQA only the final question is the only one evaluated question for each example?

Seems all other questions are just appended as context to the model.

**Comment by wenhuchen** [comment]
@MXueguang ran this experiment.

**Comment by MXueguang** [comment]
Hi @SeanNaren 
We evaluated ConvFinQA for each question. using [convfinqa_test_turn.json](https://github.com/wenhuchen/Program-of-Thoughts/blob/main/data/convfinqa_test_turn.json)
The corresponding output file is
https://github.com/wenhuchen/Program-of-Thoughts/blob/main/outputs/convfinqa_test_turn_sc_s0_e-1_11_15_10_07.jsonl

I think forgot to update this line in this repo https://github.com/wenhuchen/Program-of-Thoughts/blob/64c6bea8d6391e76b7f1182d963bbfdcba0a908f/run_convfinqa.py#L88. Fixing it now.

**Comment by SeanNaren** [comment]
This makes sense thank you! I think it makes sense to keep evaluating on the dev set, otherwise (unless I'm mistaken) you won't have labels to evaluate against.
